"""back populates removed

Revision ID: 3f9e4a7c5bd9
Revises: 0b86a9d01960
Create Date: 2026-06-23 12:22:22.366918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '3f9e4a7c5bd9'
down_revision: Union[str, Sequence[str], None] = '0b86a9d01960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
