"""reviews table

Revision ID: 4c03a8a1959f
Revises: efe27102f200
Create Date: 2026-06-24 02:46:14.898155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c03a8a1959f'
down_revision: Union[str, Sequence[str], None] = 'efe27102f200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reviews',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('postId', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['postId'], ['Posts.uid'], ),
    sa.ForeignKeyConstraint(['userId'], ['Users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reviews')
    # ### end Alembic commands ###
